title: WeCom 帮助文档
description: OpenClaw WeCom 插件使用与实现说明
remote_theme: just-the-docs/just-the-docs

url: https://yanhaidao.github.io
baseurl: /wecom

search_enabled: true
heading_anchors: true

plugins:
  - jekyll-remote-theme

aux_links:
  "GitHub 仓库":
    - "https://github.com/YanHaidao/wecom"

back_to_top: true

just_the_docs:
  heading_anchors: true
  search: true
  kramdown:
    anchor_links: true
  enable_copy_button: true
  enable_search: true

css_file: "assets/css/custom.css"
