title: WeCom 帮助文档
description: OpenClaw WeCom 插件使用与实现说明
remote_theme: just-the-docs/just-the-docs

url: https://yanhaidao.github.io
baseurl: /wecom

aux_links:
  "GitHub 仓库":
    - "https://github.com/YanHaidao/wecom"

search_enabled: true
heading_anchors: true

plugins:
  - jekyll-remote-theme

# 启用子导航，显示下拉式子标题
nav_depth: 3
